CREATE TABLE tb_token(
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    admin_token VARCHAR(100) NOT NULL,
    token_date DATETIME DEFAULT current_timestamp,
    PRIMARY KEY(Id)
);

DELIMITER $$
CREATE EVENT event1
ON SCHEDULE EVERY 1 MINUTE STARTS '2016-04-06 00:00:00'
DO 
BEGIN
DELETE FROM tb_token WHERE DATE_ADD(token_date, INTERVAL 5 MINUTE) < NOW();
END$$
DELIMITER ;
