version: "3.4"
services:
  app:
    container_name: app-a3 
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    ports:
      - "10007:10007"
    volumes:
      - "../app/:/app"
    environment:
      SECRET_KEY: secretkey
      MYSQL_ENDPOINT: mysqldb-a3
      MYSQL_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_DB: a3db
    networks: 
      - a3_net
    depends_on:
      - mysqldb-a3
    external_links:
      - mysqldb-a3:mysqldb-a3
    restart: always
    
  mysqldb-a3:
    container_name: mysqldb-a3
    image: mariadb:10.6.3
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: a3db 
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - a3_net
    volumes:
      - storage-a3-database:/var/lib/mysql

volumes:
  storage-a3-database:

networks:
  a3_net:

